// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHlWeABfZn_XxSL79AkYzufA7v0leipDo',
    appId: '1:920496785022:web:7aff8b84a11b5bbf44fa2f',
    messagingSenderId: '920496785022',
    projectId: 'livelocation-a9edd',
    authDomain: 'livelocation-a9edd.firebaseapp.com',
    storageBucket: 'livelocation-a9edd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZngky_9lh7vK9lRCv7nfXDZHnre7F8aI',
    appId: '1:920496785022:android:40cb69d70d7256e444fa2f',
    messagingSenderId: '920496785022',
    projectId: 'livelocation-a9edd',
    storageBucket: 'livelocation-a9edd.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyB6m8OjieQaSs5n9OP6nbKdYTzaCyrAvKg',
    appId: '1:920496785022:ios:e56bcc17f149752044fa2f',
    messagingSenderId: '920496785022',
    projectId: 'livelocation-a9edd',
    storageBucket: 'livelocation-a9edd.appspot.com',
    iosBundleId: 'com.example.livelocation',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6m8OjieQaSs5n9OP6nbKdYTzaCyrAvKg',
    appId: '1:920496785022:ios:e56bcc17f149752044fa2f',
    messagingSenderId: '920496785022',
    projectId: 'livelocation-a9edd',
    storageBucket: 'livelocation-a9edd.appspot.com',
    iosBundleId: 'com.example.livelocation',
  );
}
